# This file contains settings to configure the workflow.
# All file paths are relative to the "Snakemake" file for the workflow.
# Some common ones you may need to change are:
#   metadata-file
#   mzmine-batch-file
#   mzmine-spectral-libraries-import
#   mzmine-analyze-*-samples
#   skyline-process-*
#   skyline-analyze-*-samples

#############################################
# Input Data Settings
#############################################

# The path to the metadata file to check for.
# If this file does not exist, the workflow will not run.
metadata-file: metadata.csv

# The path to the directory that contains all the raw data
# from the mass spectrometry system (i.e., the ".d" directories).
raw-data-directory: raw-data


#############################################
# MSConvert Settings
#############################################

# The path to the directory that MSConvert will write the "mzML" files to.
# This directory doesn't need to exist, as Snakemake will create it if necessary.
# If you've converted some files previously, if they are found in this folder,
# the workflow can detect this and re-use the files it finds.
msconvert-output-directory: msconvert-out


#############################################
# mzMine Settings
#############################################

# The path to the mzMine batch file to use.
mzmine-batch-file: batch.xml

# Whether or not to have mzMine analyze the experimental samples.
# Any sample which is neither a blank nor a QC sample is considered experimental.
# Use "True" to include them, or "False" to exclude them.
mzmine-analyze-experimental-samples: True

# Whether or not to have mzMine analyze the QC samples.
# Any sample with "QC" in the name is considered a QC sample.
# Use "True" to include them, or "False" to exclude them.
mzmine-analyze-qc-samples: True

# Whether or not to have mzMine analyze the blank samples.
# Any sample with "blank" in the name is considered a blank sample.
# Use "True" to include them, or "False" to exclude them.
mzmine-analyze-blank-samples: True

# The path to the directory where spectral libraries are stored.
# If you're not using any, this will be ignored.
mzmine-spectral-libraries-directory: spectral-libraries

# The spectral library files to import.
# These files must all be inside the spectral libraries directory above.
#
# If you want all of them in the directory, use the following:
# mzmine-spectral-libraries-import: All
#
# If you don't want any, use the following:
# mzmine-spectral-libraries-import: None
#
# If you want to import some, specify them as follows.
# mzmine-spectral-libraries-import:
# - A-library-File.msp
# - Another-file.msp
mzmine-spectral-libraries-import: All

# The name of the directory to put the results from mzMine into.
mzmine-output-directory: mzmine-out


#############################################
# Skyline Settings
#############################################

# The directory where Skyline will output all of its results.
# This will include where the transition list and Skyline document
# get created.
skyline-output-directory: skyline-out

# The number of threads that Skyline should use for processing
# the imported data. Note: no matter what this is set to, an entire
# node will be allocated. After some performance testing, it was found
# that using a lower number of threads, but using the full node, produces
# results faster than trying to use all available threads.
skyline-thread-count: 4

# Indicates if Skyline should be run using the raw ".d" folders or not.
# Use "True" if it should be run, and "False" if not.
# The raw ".d" folders to analyze will come from the "raw-data-directory" setting.
skyline-process-raw-data: False

# Indicates if Skyline should be run using the ".mzML" files or not.
# Use "True" if it should be run, and "False" if not.
# The ".mzML" files to analyze will come from the "msconvert-output-directory" setting.
skyline-process-mzml-files: False

# Whether or not to have Skyline analyze the experimental samples.
# Any sample which is neither a blank nor a QC sample is considered experimental.
# Use "True" to include them, "False" to exclude them,
# or "CopyMZMine" to copy the similar setting from the mzMine section.
skyline-analyze-experimental-samples: True

# Whether or not to have Skyline analyze the QC samples.
# Any sample with "QC" in the name is considered a QC sample.
# Use "True" to include them, "False" to exclude them,
# or "CopyMZMine" to copy the similar setting from the mzMine section.
skyline-analyze-qc-samples: True

# Whether or not to have Skyline analyze the blank samples.
# Any sample with "blank" in the name is considered a blank sample.
# Use "True" to include them, "False" to exclude them,
# or "CopyMZMine" to copy the similar setting from the mzMine section.
skyline-analyze-blank-samples: True
