#############################################
# Input Data Settings
#############################################

# The name of the metadata file to check for.
metadata-file: config/metadata.csv

# The name of the directory that contains all the raw data
# from the mass spectrometry system (i.e., the ".d" directories).
raw-data-directory: raw-data


#############################################
# MSConvert Settings
#############################################

# The name of the directories to put the results from MSConvert into.
msconvert-output-directory: msconvert-out


#############################################
# mzMine Settings
#############################################

# The name of the mzMine batch file to use.
mzmine-batch-file: config/batch.xml

# The name of the directory where spectral libraries are stored.
mzmine-spectral-libraries-directory: spectral-libraries

# The name of the directory to put the results from mzMine into.
mzmine-output-directory: mzmine-out
